---
name: Module Test

on: [workflow_call]

jobs:
  build:
    name: Module Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.6.15"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependences from pip
      shell: bash
      run: pip install ansible pytest coveralls mock requests coverage
    - name: NIFCLOUD modules check
      shell: bash
      run: |
        coverage run --source=library -m pytest library/tests/
        coverage xml
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        format: cobertura
